
class AuthException(Exception):
    pass


class NotFoundException(Exception):
    pass
